#!/usr/bin/env node

const path = require('path')
const hhp = require('hhp')
const log = require('./log')
const { getFileSrc } = require('./utils')

const filename = process.argv[2]

getFileSrc(filename, onfileSrc)

function onfileSrc(err, src) {
  if (err) return console.error(err)

  const handHistories = hhp.extractHands(src.toString())
  console.error('Parsing %d hand histories from %s', handHistories.length, path.basename(filename))

  const parsed = handHistories.map(hhp).filter(x => !!x)
  console.error('Adding %d parsed hands', parsed.length)

  log.addHands(parsed, onadded)

  function onadded() {
    console.log('done')
  }
}
